#!/usr/bin/env python

import logging
log = logging.getLogger(__name__)

import os
import testbase
import time
import utils

import psycopg2

class TestPostgresql(testbase.TestBase):
  def __init__(self, protocol=None):
    super(TestPostgresql, self).__init__()
    self.bundle_type = 'pg'
    self.proxy_charm = 'cs:~justin-fathomdb/trusty/postgresql-proxy'
    self.consumer_charm = 'cs:~justin-fathomdb/trusty/python-django'
    self.juju_interface = 'pgsql'
    if protocol:
      self.proxy_properties['protocol'] = protocol

  def create_consumer_relation(self):
    utils.juju_ensure_relation('%s:db' % self.proxy_service_name, '%s' % self.consumer_service_name)

  def _db_connect(self, relinfo):
    conn_string = "host='%s' dbname='%s' user='%s' password='%s'" % (
                  relinfo.get('host'), relinfo.get('database'), relinfo.get('user'), relinfo.get('password'))
    log.info("Connecting to postgres %s", conn_string)

    connection = psycopg2.connect(conn_string)
    connection.autocommit = True
    return connection

  def _execute_sql(self, db, sql, fetch=True):
    log.info("Running SQL: %s", sql)
    cur = db.cursor()
    cur.execute(sql)
    rows = None
    if fetch:
      rows = cur.fetchall()
    cur.close()
    return rows

  def check_service_state_consumer(self):
    relinfo = self.get_relation_properties()
    self._run_test_sql(relinfo)

  def check_service_state_proxy(self):
    relinfo = self.get_relation_properties()
    db = self._db_connect(relinfo)
    self._execute_sql(db, 'SELECT 1');

  def _run_test_sql(self, relinfo):
    db = self._db_connect(relinfo)
    self._execute_sql(db, 'CREATE TABLE IF NOT EXISTS test1 (id int)', fetch=False)

    self._execute_sql(db, 'DELETE FROM test1', fetch=False)
    for i in xrange(10):
      self._execute_sql(db, 'INSERT INTO test1 VALUES (1)', fetch=False)

    for i in xrange(12):
      self._execute_sql(db, 'INSERT INTO test1 SELECT * FROM test1', fetch=False)

    rows = self._execute_sql(db, 'SELECT * FROM test1')
    log.info("Rows %s", len(rows))
    assert len(rows) > 40000

  # TODO
  def change_properties(self):
    pass

  def inject_fault(self):
    utils.juju_ssh(self.backend_main_service_name, '0', ['sudo', 'service', 'postgresql', 'stop'])
    time.sleep(5)

t = TestPostgresql(protocol=os.environ.get('TEST_PROTOCOL'))
t.run_test()
