#!/bin/bash

set -e
set -x

if [[ ! -d apps/spring-music ]]; then
  mkdir -p apps
  pushd apps
  git clone https://github.com/cloudfoundry-samples/spring-music.git
  popd
fi

pushd apps/spring-music
./gradlew assemble
cf push spring-music -n spring-music
popd

function teardown() {
  echo "Cleaning up"
  cf delete -f spring-music
  cf delete-service -f mysql1
  cf delete-service-broker -f jxaas-mysql

  # Give the service a bit of time to stop, before we stop jxaas
  sleep 20
}

trap "teardown" EXIT

cf create-service-broker jxaas-mysql admin admin http://10.0.3.1:8080/cf/mysql

# Should include mysql
cf service-access | grep mysql

cf enable-service-access mysql
cf service-access | grep mysql | grep all

# Should include Nirvana:
curl http://spring-music.10.244.0.34.xip.io/albums | grep Nirvana

# Should include 'in-memory', not 'mysql'
curl http://spring-music.10.244.0.34.xip.io/info | grep memory

cf create-service mysql nano mysql1
cf services
cf bind-service spring-music mysql1

cf restage spring-music

# Should include Nirvana:
curl http://spring-music.10.244.0.34.xip.io/albums | grep Nirvana

# Should include 'mysql', not 'in-memory':
curl http://spring-music.10.244.0.34.xip.io/info | grep mysql

cf unbind-service spring-music mysql1
cf restage spring-music

# Should include Nirvana:
curl http://spring-music.10.244.0.34.xip.io/albums | grep Nirvana

# Should include 'in-memory', not 'mysql'
curl http://spring-music.10.244.0.34.xip.io/info | grep memory

